/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;

/**
 *
 * @author admin
 */
public class main_screen extends javax.swing.JFrame {

    /**
     * Creates new form main_screen
     */
    public main_screen() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientsB = new javax.swing.JButton();
        pharmacyB = new javax.swing.JButton();
        financeB = new javax.swing.JButton();
        doctorB = new javax.swing.JButton();
        logoutB = new javax.swing.JButton();
        titleL = new javax.swing.JLabel();
        subTitleL = new javax.swing.JLabel();
        photoL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        patientsB.setText("Patients");
        patientsB.setPreferredSize(new java.awt.Dimension(80, 23));
        patientsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsBActionPerformed(evt);
            }
        });

        pharmacyB.setText("Pharmacy");
        pharmacyB.setPreferredSize(new java.awt.Dimension(80, 23));
        pharmacyB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacyBActionPerformed(evt);
            }
        });

        financeB.setText("Finances");
        financeB.setPreferredSize(new java.awt.Dimension(80, 23));
        financeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financeBActionPerformed(evt);
            }
        });

        doctorB.setText("Doctors");
        doctorB.setPreferredSize(new java.awt.Dimension(80, 23));
        doctorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorBActionPerformed(evt);
            }
        });

        logoutB.setText("LogOut");
        logoutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBActionPerformed(evt);
            }
        });

        titleL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleL.setText("St John's Hospital");

        subTitleL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subTitleL.setText("Administavtive Program");

        photoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/main_pic.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doctorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(financeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pharmacyB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientsB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoL, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleL))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoutB)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(subTitleL)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(patientsB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(pharmacyB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(financeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(doctorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(titleL)
                        .addGap(18, 18, 18)
                        .addComponent(subTitleL)
                        .addGap(18, 18, 18)
                        .addComponent(photoL, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(logoutB)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsBActionPerformed
        patient_screen Patient = new patient_screen();
        Patient.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_patientsBActionPerformed

    private void pharmacyBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacyBActionPerformed
        pharmacy_screen Pharmacy = new pharmacy_screen();
        Pharmacy.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pharmacyBActionPerformed

    private void financeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financeBActionPerformed
        finances_screen Fin = new finances_screen();
        Fin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_financeBActionPerformed

    private void doctorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorBActionPerformed
        doctors_screen Doc = new doctors_screen();
        Doc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_doctorBActionPerformed

    private void logoutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBActionPerformed
        login_screen login = new login_screen();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doctorB;
    private javax.swing.JButton financeB;
    private javax.swing.JButton logoutB;
    private javax.swing.JButton patientsB;
    private javax.swing.JButton pharmacyB;
    private javax.swing.JLabel photoL;
    private javax.swing.JLabel subTitleL;
    private javax.swing.JLabel titleL;
    // End of variables declaration//GEN-END:variables
}
